version: "3"

services:
  mysql:
    #restart: always
    #container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - LANG=C.UTF-8  
    ports:
      - 3306:3306  
      
  app:
    #container_name: app
    restart: always
    image: ilanacabral/osworks-api
    #ports:
    #  - "8080:8080"
    depends_on: 
      - mysql      
     
  nginx:
    #container_name: nginx
    restart:  on-failure
    image: ilanacabral/nginx    
    ports:
      - 8080:80
    depends_on: 
      - app
    
 